version: "3.9"
services:

  nginx:
    image: nginx
    ports:
      - "80:80"

  rabbitmq_list:
    image: rabbitmq
    ports:
      - "5672:5672"
  
  create_user:
    build: create_user/
    ports:
      - "5000:5000" 
    links:
      - "rabbitmq_list"
